#!/bin/sh

PATH=/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin

. /etc/default/xbian-snap

[ "$ENABLEDSCHEDULE" = yes ] || exit 0

while initctl list | grep "^xbian-xbmc-player" | grep -q "start/running"; do
  if status xbmc-screensaver | grep -q "start/running"; then
    break
  fi
  sleep 300 # 5 minutes
done

if [ -z "$EXCLUDESUB" ];
then
  TMPEXCLUDESUB=
else
  TMPEXCLUDESUB="-x $EXCLUDESUB"
fi

[ "$KEEPDAYS" -gt 0 ] && btrfs-auto-snapshot -l daily -k $KEEPDAYS -v $TMPEXCLUDESUB //

if [ "$IMGPLAN" = daily ]; then
  [ "$IMGTYPE" = file ] && opt_img='--img' || IMGKEEP=0
  nice -n +1 /usr/sbin/btrfs-auto-snapshot xbiancopy $opt_img /dev/root $IMGDEST > /dev/null 2>&1
  xbian-config xbiancopy doclean "$(xbian-config xbiancopy imgdest)" $IMGKEEP
fi

if [ "$HOMEPLAN" = daily ]; then
  nice -n +1 /usr/sbin/btrfs-auto-snapshot backuphome $HOMEDEST > /dev/null 2>&1
  xbian-config xbiancopy doclean "$(xbian-config xbiancopy homedest)" $HOMEKEEP
fi
