#!/bin/bash
#
#Copyright 2012 - 2017 CurlyMo & mkreisl <development@xbian.org>
#
#This file is part of XBian - XBMC on the Raspberry Pi.
#
#XBian is free software: you can redistribute it and/or modify it under the
#terms of the GNU General Public License as published by the Free Software
#Foundation, either version 3 of the License, or (at your option) any later
#version.
#
#XBian is distributed in the hope that it will be useful, but WITHOUT ANY
#WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
#FOR A PARTICULAR PURPOSE. See the GNU General Public License for more
#details.
#
#You should have received a copy of the GNU General Public License along
#with XBian. If not, see <http://www.gnu.org/licenses/>

# Get the current password
#  $1 [String] New password
# Returns
#  * [Integer]
#  - 1: Success
#  - 0: Failed
function setXbianPassFn() {
	rc=0
	if which vncpasswd >/dev/null; then
		mkdir -p /home/xbian/.vnc
		echo $1 | vncpasswd -f > /home/xbian/.vnc/passwd
		rc=$(($rc+$?))
	fi
	echo "xbian:$1" | chpasswd
	rc=$(($rc+$?))
	[ $rc == 0 ] && return 1 || return 0
}
