#!/bin/sh

. /etc/default/xbian-snap

[ "$ENABLEDSCHEDULE" = yes ] || exit 0
[ "$KEEPWEEKS" -ne 0 ] || exit 0

while initctl list | grep "^xbian-xbmc-player" | grep -q "start/running"; do
  if status xbmc-screensaver | grep -q "start/running"; then
    break
  fi
  sleep 300 # 5 minutes
done

if [ -z "$EXCLUDESUB" ];
then
  TMPEXCLUDESUB=
else
  TMPEXCLUDESUB="-x $EXCLUDESUB"
fi
btrfs-auto-snapshot -l weekly -k $KEEPWEEKS -v $TMPEXCLUDESUB //
