#!/bin/bash

if [ $1 = "configure" ]; then


    find /usr/local/bin -lname /usr/local/bin/busybox -exec rm {} +
    /usr/local/bin/busybox --list | grep -v 'udhcp\|rpm\|rpm2cpio' | xargs -L1 -I%% sh -c 'which %% >/dev/null|| ln -s /usr/local/bin/busybox /usr/local/bin/%%'

	date > /home/xbian/xbian-config-update.log

	[ -e /usr/share/locale/en/LC_MESSAGES/ ] || mkdir -p /usr/share/locale/en/LC_MESSAGES/

        echo "Installing language files..."
	for l in $(find /usr/local/include/xbian-config/gettext -type f -name "*.po"); do
	    a=$(basename $l)
	    a=${a#*\.};a=${a%\.*}
	    echo $a
	    [ -d /usr/share/locale/$a/LC_MESSAGES ] && msgfmt -o /usr/share/locale/$a/LC_MESSAGES/xbian.mo $l
	done

	. /etc/bash_completion.d/xbian-config.sh >/dev/null

        /usr/sbin/btrfs-auto-snapshot listvol | grep -qx data || { /usr/sbin/btrfs-auto-snapshot createvol data; /usr/sbin/btrfs-auto-snapshot createvol data/@; }

        [ -e /home/xbian/.bashrc ] || touch /home/xbian/.bashrc

        if [ ! -e /home/xbian/.xbian-config-start ]; then
            if grep -q "#sudo xbian-config" /home/xbian/.bashrc; then
                echo '0' > /home/xbian/.xbian-config-start
            else
                echo '1' > /home/xbian/.xbian-config-start
            fi

            chown xbian:xbian /home/xbian/.xbian-config-start > /dev/null
        fi

        sed -i '/sudo xbian-config/d' /home/xbian/.bashrc
        grep -q "/home/xbian/.xbian-config-start.sh" /home/xbian/.bashrc || echo ". /home/xbian/.xbian-config-start.sh" >> /home/xbian/.bashrc
        chown xbian:xbian /home/xbian/.bashrc

    rm -f /etc/apt/apt.conf.d/20apt-show-versions

    # update config
    if [ ! -e /etc/default/xbian-snap ]; then
        mv /var/tmp/xbian-snap /etc/default/xbian-snap
    else
        if grep -q "ENABLEDSCHEDULE=" /etc/default/xbian-snap; then
            us="$(grep ENABLEDSCHEDULE= /etc/default/xbian-snap)"
            eval $(echo "sed -i 's%ENABLEDSCHEDULE=yes%$us%' /var/tmp/xbian-snap")
        fi
        if grep -q "KEEPDAYS=" /etc/default/xbian-snap; then
            us=$(grep KEEPDAYS= /etc/default/xbian-snap)
            eval $(echo "sed -i 's%KEEPDAYS=3%$us%' /var/tmp/xbian-snap")
        fi
        if grep -q "KEEPWEEKS=" /etc/default/xbian-snap; then
            us=$(grep KEEPWEEKS= /etc/default/xbian-snap )
            eval $(echo "sed -i 's%KEEPWEEKS=2%$us%' /var/tmp/xbian-snap")
        fi
        if grep -q "KEEPMONTHS=" /etc/default/xbian-snap; then
            us=$(grep KEEPMONTHS= /etc/default/xbian-snap )
            eval $(echo "sed -i 's%KEEPMONTHS=0%$us%' /var/tmp/xbian-snap")
        fi
        if grep -q "ENABLEDAPT=" /etc/default/xbian-snap; then
            us=$(grep ENABLEDAPT= /etc/default/xbian-snap)
            eval $(echo "sed -i 's%ENABLEDAPT=yes%$us%' /var/tmp/xbian-snap")
        fi
        if grep -q "KEEPAPT=" /etc/default/xbian-snap; then
            us=$(grep KEEPAPT= /etc/default/xbian-snap)
            eval $(echo "sed -i 's%KEEPAPT=10%$us%' /var/tmp/xbian-snap")
        fi
        if grep -q "IMGPLAN=" /etc/default/xbian-snap; then
            us=$(grep IMGPLAN= /etc/default/xbian-snap)
            eval $(echo "sed -i 's%IMGPLAN=none%$us%' /var/tmp/xbian-snap")
        fi
        if grep -q "IMGTYPE=" /etc/default/xbian-snap; then
            us=$(grep IMGTYPE= /etc/default/xbian-snap)
            eval $(echo "sed -i 's%IMGTYPE=notset%$us%' /var/tmp/xbian-snap")
        fi
        if grep -q "IMGDEST=" /etc/default/xbian-snap; then
            IFS=$'\n'
            us=$(grep IMGDEST= /etc/default/xbian-snap | awk -F'=' '{print $2}' | tr -d \")
            eval sed -i 's\@IMGDEST=.*@IMGDEST=\"$us\"@' /var/tmp/xbian-snap
            unset IFS
        fi

        mv /var/tmp/xbian-snap /etc/default/xbian-snap
    fi
    :

    if [ -e /etc/inetd.conf ]; then
        grep -v "netbios-ns dgram udp wait root /usr/sbin/nmbd nmbd" /etc/inetd.conf > /etc/inetd.conf.new
        mv /etc/inetd.conf.new /etc/inetd.conf
    fi
    insserv -f samba >/dev/null 2>&1

    if ! [ -f /home/xbian/.profile ]; then
cat << \EOF > /home/xbian/.profile
if [ -n "$BASH_VERSION" ]; then
    # include .bashrc if it exists
    if [ -f "$HOME/.bashrc" ]; then
        . "$HOME/.bashrc"
    fi
fi
EOF
    fi
fi

exit 0
