#!/bin/bash

CONFD="/usr/local/include/xbian-config/config"

if [ $1 = "configure" ]; then

    find /usr/local/bin -lname /usr/local/bin/busybox -exec rm {} +
    /usr/local/bin/busybox --list | grep -v 'udhcp\|rpm\|rpm2cpio' | xargs -L1 -I%% sh -c 'which %% >/dev/null|| ln -s /usr/local/bin/busybox /usr/local/bin/%%'

	date > /home/xbian/xbian-config-update.log

	[ -e /usr/share/locale/en/LC_MESSAGES/ ] || mkdir -p /usr/share/locale/en/LC_MESSAGES/

        echo -n "Installing language files ( "
	for l in $(find /usr/local/include/xbian-config/gettext -type f -name "*.po"); do
	    a=$(basename $l)
	    a=${a#*\.};a=${a%\.*}
	    echo -n "$a "
	    [ -d /usr/share/locale/$a/LC_MESSAGES ] && msgfmt -o /usr/share/locale/$a/LC_MESSAGES/xbian.mo $l
	done
	echo ")"

	. /etc/bash_completion.d/xbian-config.sh >/dev/null

        /usr/sbin/btrfs-auto-snapshot listvol | grep -qx data || { /usr/sbin/btrfs-auto-snapshot createvol data; /usr/sbin/btrfs-auto-snapshot createvol data/@; }

        [ -e /home/xbian/.bashrc ] || touch /home/xbian/.bashrc

        if [ ! -e /home/xbian/.xbian-config-start ]; then
            if grep -q "#sudo xbian-config" /home/xbian/.bashrc; then
                echo '0' > /home/xbian/.xbian-config-start
            else
                echo '1' > /home/xbian/.xbian-config-start
            fi

            chown xbian:xbian /home/xbian/.xbian-config-start > /dev/null
        fi

        sed -i '/sudo xbian-config/d' /home/xbian/.bashrc
        grep -q "/home/xbian/.xbian-config-start.sh" /home/xbian/.bashrc || echo ". /home/xbian/.xbian-config-start.sh" >> /home/xbian/.bashrc
        chown xbian:xbian /home/xbian/.bashrc

    rm -f /etc/apt/apt.conf.d/20apt-show-versions

    # update config
    if [ -e /etc/default/xbian-snap ]; then
        if grep -q "ENABLEDSCHEDULE=" /etc/default/xbian-snap; then
            us="$(grep ENABLEDSCHEDULE= /etc/default/xbian-snap)"
            eval $(echo "sed -i 's%ENABLEDSCHEDULE=yes%$us%' /var/tmp/xbian-snap")
        fi
        if grep -q "KEEPDAYS=" /etc/default/xbian-snap; then
            us=$(grep KEEPDAYS= /etc/default/xbian-snap)
            eval $(echo "sed -i 's%KEEPDAYS=3%$us%' /var/tmp/xbian-snap")
        fi
        if grep -q "KEEPWEEKS=" /etc/default/xbian-snap; then
            us=$(grep KEEPWEEKS= /etc/default/xbian-snap )
            eval $(echo "sed -i 's%KEEPWEEKS=2%$us%' /var/tmp/xbian-snap")
        fi
        if grep -q "KEEPMONTHS=" /etc/default/xbian-snap; then
            us=$(grep KEEPMONTHS= /etc/default/xbian-snap )
            eval $(echo "sed -i 's%KEEPMONTHS=0%$us%' /var/tmp/xbian-snap")
        fi
        if grep -q "ENABLEDAPT=" /etc/default/xbian-snap; then
            us=$(grep ENABLEDAPT= /etc/default/xbian-snap)
            eval $(echo "sed -i 's%ENABLEDAPT=yes%$us%' /var/tmp/xbian-snap")
        fi
        if grep -q "KEEPAPT=" /etc/default/xbian-snap; then
            us=$(grep KEEPAPT= /etc/default/xbian-snap)
            eval $(echo "sed -i 's%KEEPAPT=10%$us%' /var/tmp/xbian-snap")
        fi
        if grep -q "IMGPLAN=" /etc/default/xbian-snap; then
            us=$(grep IMGPLAN= /etc/default/xbian-snap)
            eval $(echo "sed -i 's%IMGPLAN=none%$us%' /var/tmp/xbian-snap")
        fi
        if grep -q "IMGTYPE=" /etc/default/xbian-snap; then
            us=$(grep IMGTYPE= /etc/default/xbian-snap)
            eval $(echo "sed -i 's%IMGTYPE=notset%$us%' /var/tmp/xbian-snap")
        fi
        if grep -q "IMGDEST=" /etc/default/xbian-snap; then
            SAVEIFS=$IFS
            IFS=$'\n'
            us=$(grep IMGDEST= /etc/default/xbian-snap | awk -F'=' '{print $2}' | tr -d \")
            eval sed -i 's\@IMGDEST=.*@IMGDEST=\"$us\"@' /var/tmp/xbian-snap
            IFS=$SAVEIFS
        fi
        if grep -q "IMGKEEP=" /etc/default/xbian-snap; then
            us=$(grep IMGKEEP= /etc/default/xbian-snap)
            eval $(echo "sed -i 's%IMGKEEP=0%$us%' /var/tmp/xbian-snap")
        fi
        if grep -q "HOMEPLAN=" /etc/default/xbian-snap; then
            us=$(grep HOMEPLAN= /etc/default/xbian-snap)
            eval $(echo "sed -i 's%HOMEPLAN=none%$us%' /var/tmp/xbian-snap")
        fi
        if grep -q "HOMEDEST=" /etc/default/xbian-snap; then
            SAVEIFS=$IFS
            IFS=$'\n'
            us=$(grep HOMEDEST= /etc/default/xbian-snap | awk -F'=' '{print $2}' | tr -d \")
            eval sed -i 's\@HOMEDEST=.*@HOMEDEST=\"$us\"@' /var/tmp/xbian-snap
            IFS=$SAVEIFS
        fi
        if grep -q "HOMEKEEP=" /etc/default/xbian-snap; then
            us=$(grep HOMEKEEP= /etc/default/xbian-snap)
            eval $(echo "sed -i 's%HOMEKEEP=0%$us%' /var/tmp/xbian-snap")
        fi
    fi
    mv /var/tmp/xbian-snap /etc/default/xbian-snap

    [ -e /etc/default/samba.preinst ] && mv /etc/default/samba.preinst /etc/default/samba
    PARMS=$(sed 's/^[ \t]*//;/^#/d;/^$/d;s/=.*//' /var/tmp/samba)
    if [ -e /etc/default/samba ]; then
        for PARM in $PARMS; do
            if grep -q ^$PARM= /etc/default/samba; then
                p=$(grep ^"$PARM=" /etc/default/samba)
                sed -i "s%^$PARM=.*%$p%g" /var/tmp/samba
            fi
        done
    fi
    chown xbian:xbian /var/tmp/samba

    [ -e /tmp/services ] && mv /tmp/services $CONFD/

    [ -e /etc/inetd.conf ] && sed -i '/netbios-ns dgram udp wait root \/usr\/sbin\/nmbd nmbd/d' /etc/inetd.conf

    insserv -f samba >/dev/null 2>&1

    if ! [ -f /home/xbian/.profile ]; then
cat << \EOF > /home/xbian/.profile
if [ -n "$BASH_VERSION" ]; then
    # include .bashrc if it exists
    if [ -f "$HOME/.bashrc" ]; then
        . "$HOME/.bashrc"
    fi
fi
EOF
    fi

    dpkg-trigger --no-await trigger-xbian-package-config-shell

elif [ $1 = "triggered" ]; then
    [ -e /var/tmp/samba ] && mv /var/tmp/samba /etc/default/
    . /etc/default/samba
    if [ "$RUN_MODE" = inetd ]; then
        if [ -e $CONFD/.samba.inetd ]; then # We have to switch from upstart job to inetd
            [ -e $CONFD/samba.inetd ] && mv $CONFD/samba.inetd $CONFD/.samba.inetd
            rs=$(xbian-config services status samba | awk '{ print $2 }')
            case $rs in
                4|5) xbian-config services stop samba >/dev/null ;;
            esac
            mv $CONFD/.samba.inetd $CONFD/samba.inetd
            sed -i 's/samba:.*/samba:%%inetd/g' $CONFD/services
            case $rs in
                3|4|5) xbian-config services autostart samba enable  >/dev/null ;;
                *)     xbian-config services autostart samba disable >/dev/null ;;
            esac
        fi
    else
        if [ ! -e $CONFD/.samba.inetd ]; then # We have to switch from inetd to upstart job
            rs=$(xbian-config services status samba | awk '{ print $2 }')
            case $rs in
                4|5) xbian-config services autostart samba disable >/dev/null ;;
            esac
            [ -e $CONFD/samba.inetd ] && mv $CONFD/samba.inetd $CONFD/.samba.inetd
            sed -i 's/samba:.*/samba::smbd/g' $CONFD/services
            SC=/etc/init/smbd.conf; [ "$(stat -c %s $SC)" -eq 0 -a -e $SC.dpkg-dist ] && mv $SC.dpkg-dist $SC
            case $rs in
                3|5) xbian-config services autostart samba enable  >/dev/null ;;
                *)   xbian-config services autostart samba disable >/dev/null ;;
            esac
            [ "$rs" -gt 3 ] && xbian-config services start samba >/dev/null
        fi
    fi
fi

exit 0
