#!/bin/bash
#
#Copyright 2012 CurlyMo <development@xbian.org>
#
#This file is part of XBian - XBMC on the Raspberry Pi.
#
#XBian is free software: you can redistribute it and/or modify it under the
#terms of the GNU General Public License as published by the Free Software
#Foundation, either version 3 of the License, or (at your option) any later
#version.
#
#XBian is distributed in the hope that it will be useful, but WITHOUT ANY
#WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
#FOR A PARTICULAR PURPOSE. See the GNU General Public License for more
#details.
#
#You should have received a copy of the GNU General Public License along
#with XBian. If not, see <http://www.gnu.org/licenses/>

function setEnableAuto() {
	if [ -z "$1" ]; then
	    [ -e /etc/apt/apt.conf.d/10xbian-periodic ] && return $(grep "APT::Periodic::Unattended-Upgrade" /etc/apt/apt.conf.d/10xbian-periodic | grep -o "[0-9]*") || return 0
	else
            grep -v "APT::Periodic::Unattended-Upgrade" /etc/apt/apt.conf.d/10xbian-periodic > /etc/apt/apt.conf.d/10xbian-periodic.new
            mv /etc/apt/apt.conf.d/10xbian-periodic.new /etc/apt/apt.conf.d/10xbian-periodic
	    echo "APT::Periodic::Unattended-Upgrade \"$1\";" >> /etc/apt/apt.conf.d/10xbian-periodic
	    [ "$(xbian-config updates enableauto)" = "$1" ] && return 1 || return 0
	fi
}

function setEnableInventoryAuto() {
	if [ -z "$1" ]; then
	    [ -e /etc/apt/apt.conf.d/10xbian-periodic ] && return $(grep "APT::Periodic::Update-Package-Lists" /etc/apt/apt.conf.d/10xbian-periodic | grep -o "[0-9]*") || return 0
	else
	    [ $1 -ne 0 ] && int=$2 || int=0
            grep -v "APT::Periodic::Update-Package-Lists" /etc/apt/apt.conf.d/10xbian-periodic > /etc/apt/apt.conf.d/10xbian-periodic.new
            mv /etc/apt/apt.conf.d/10xbian-periodic.new /etc/apt/apt.conf.d/10xbian-periodic
	    echo "APT::Periodic::Update-Package-Lists \"$int\";" >> /etc/apt/apt.conf.d/10xbian-periodic
	    [ $(grep "APT::Periodic::Update-Package-Lists" /etc/apt/apt.conf.d/10xbian-periodic | grep -o "[0-9]*") = "$int" ] && return 1 || return 0
	fi
}

function setSnapApt(){
    if [ -z "$1" ]; then 
	grep -q ENABLEDAPT=yes /etc/default/xbian-snap && return 1 || return 0
    else
	cs=$(grep ENABLEDAPT= /etc/default/xbian-snap)
	[ $1 -eq 1 ] && sed -i 's/ENABLEDAPT=.*/ENABLEDAPT=yes/' /etc/default/xbian-snap && return $(xbian-config updates snapapt)
	[ $1 -eq 0 ] && sed -i 's/ENABLEDAPT=.*/ENABLEDAPT=no/' /etc/default/xbian-snap && return $((1 - $(xbian-config updates snapapt) ))
    fi
}

function retrieveUpdateListFn() {
	xbian-apt-show-versions -u >/tmp/aptupdates 2>/dev/null
        apt-mark showhold > /tmp/apthold
}

function getAllPackagesLisFn() {
	if [ -f "/tmp/aptupdates" ]; then
		PACKAGES=($(grep -vw -f /tmp/apthold /tmp/aptupdates | sed 's/\/[a-z]*//g' | awk '{print $1";"$2";"$5}' | sort | uniq));
                [ -z "${PACKAGES[0]}" ] && unset PACKAGES
		return 1;
	else
		return 0;
	fi
}

function getAllUpdatesLisFn() {
        getAllPackagesLisFn
}

function updatePackagesFn() {
	LIST="";
        if [ "$2" = '-' ]; then
            lt=${!PACKAGES[@]}
            d=0
        else
            lt=$2
            d=1
        fi

        ARRAY=($lt);
        for INDEX in ${ARRAY[@]}; do
		INDEX=${INDEX/\\/}
		INDEX=$(echo $INDEX | tr -d "\"")
		NAME=$(echo ${PACKAGES[$((INDEX-$d))]} | cut -f1 -d";");
		VERSION=$(echo ${PACKAGES[$((INDEX-$d))]} | cut -f3 -d";");
		LIST+=" "$NAME"="$VERSION
	done;

	if [ $1 -eq 1 ]; then
		eval apt-get install -s $LIST>/tmp/aptstatus
	elif [ $1 -eq 0 ]; then
		{ rm -f /tmp/aptupdates; DEBIAN_FRONTEND=noninteractive eval apt-get install -y -o Dpkg::Options::="--force-confdef" -o Dpkg::Options::="--force-confold" $LIST; } | tee /tmp/aptstatus | dialog --progressbox $(tput lines) $(tput cols)
	elif [ $1 -eq 2 ]; then
		{ DEBIAN_FRONTEND=noninteractive eval nohup apt-get install -y -o Dpkg::Options::="--force-confdef" -o Dpkg::Options::="--force-confold" $LIST; rm -f /tmp/aptupdates; } >/tmp/aptstatus &
	fi
        getAptErrorCodeFn
        return $?
}

function findNextUpdateVersionFn() {
	CMAJVERSION=$1;
	CMINVERSION=$2;
	ISALPHA=$(echo $CMINVERSION | grep -c "\.");
	ISBETA=0;
	ISSTABLE=0;
	NEXTVERSION="";
	NEXTBETA=0;
	NEXTALPHA=0;
	NEXTMINSTABLE=0;
	NEXTMAJSTABLE=0;
	if [ $ISALPHA -eq 0 ]; then
		if [ ! -z "$CMINVERSION" ]; then
			ISBETA=1;
		fi
	fi
	if [ $ISALPHA -eq 0 ] && [ $ISBETA -eq 0 ]; then
		ISSTABLE=1;
	fi

	if [ $ISSTABLE -eq 1 ]; then
		NEXTALPHA=0.1;
		CMAJVERSION=$(echo "$CMAJVERSION+0.1" | bc);
	elif [ $ISBETA -eq 1 ]; then
		NEXTALPHA=$(echo "$CMINVERSION+0.1" | bc);
	elif [ $ISALPHA -eq 1 ]; then
		CURBETA=$(echo $CMINVERSION | cut -f1 -d".");
		NEXTALPHA=$(echo $CMINVERSION | cut -f2 -d".");
		NEXTALPHA=$(echo "$NEXTALPHA+1" | bc);
		NEXTALPHA=$CURBETA"."$NEXTALPHA;
	fi

	if [ $(cat "$BASEPATH/config/pkglist" | grep -c "xbian-update_"$CMAJVERSION"-"$NEXTALPHA"_") -eq 1 ]; then
		NEXTVERSION=$CMAJVERSION-$NEXTALPHA;
	fi
	
	if [ -z "$NEXTVERSION" ]; then
		if [ $ISSTABLE -eq 1 ]; then
			NEXTBETA=1;
		elif [ $ISBETA -eq 1 ]; then
			NEXTBETA=$(echo "$CMINVERSION+1" | bc);
		elif [ $ISALPHA -eq 1 ]; then
			NEXTBETA=$(echo $CMINVERSION | cut -f1 -d".");
			NEXTBETA=$(echo "$NEXTBETA+1" | bc);
		fi
	fi
	if [ $(cat "$BASEPATH/config/pkglist" | grep -c "xbian-update_"$CMAJVERSION"-"$NEXTBETA"_") -eq 1 ]; then
		NEXTVERSION=$CMAJVERSION-$NEXTBETA;
	fi
	if [ -z "$NEXTVERSION" ]; then
		if [ $ISSTABLE -eq 0 ]; then
			NEXTMINSTABLE=$(echo "$CMAJVERSION+0.1" | bc);
		else
			NEXTMINSTABLE=$CMAJVERSION;
		fi
	fi
	if [ $(cat "$BASEPATH/config/pkglist" | grep -c "xbian-update_"$NEXTMINSTABLE"_") -eq 1 ]; then
		NEXTVERSION=$NEXTMINSTABLE;
	fi	
	if [ -z "$NEXTVERSION" ]; then
		CMAJVERSION=$(echo "$CMAJVERSION" | cut -f1 -d"." | bc);
		NEXTMAJSTABLE=$(echo "$CMAJVERSION+1" | bc);
	fi
	if [ $(cat "$BASEPATH/config/pkglist" | grep -c "xbian-update_"$NEXTMINSTABLE"_") -eq 1 ]; then
		NEXTVERSION=$NEXTMAJSTABLE;
	fi
}


function updateSystemFn() {
	LIST="";
	ARRAY=($2);
	NEXTVERSION="";
	if [ ${#ARRAY[@]} -gt 0 ]; then
#		INDEX=${ARRAY[0]};
#		INDEX=${INDEX/\\/}
#		INDEX=$(echo $INDEX | tr -d "\"")
		INDEX=1
		NVERSION=$(echo ${UPDATES[$((INDEX-1))]} | cut -f3 -d";");
		CVERSION=$(echo ${UPDATES[$((INDEX-1))]} | cut -f2 -d";");
		CMAJVERSION=$(echo $CVERSION | cut -f1 -d"-");
		CMINVERSION=$(echo $CVERSION | cut -f2 -d"-");

#		findNextUpdateVersionFn "$CMAJVERSION" "$CMINVERSION";
		VERSIONS=($(echo ${UPDATES[$((INDEX-1))]} | cut -f1 -d";"))
		NEXTVERSION=$NVERSION
	fi

	if [ -z "$NEXTVERSION" ]; then
		return 2;
	else 
		touch /run/noreboot
		if [ $1 -eq 1 ]; then
			DEBIAN_FRONTEND=noninteractive eval apt-get install -s ${VERSIONS[0]}"="$NEXTVERSION >/tmp/aptstatus
		elif [ $1 -eq 0 ]; then
			{ rm -f /tmp/aptupdates; DEBIAN_FRONTEND=noninteractive eval apt-get install -y ${VERSIONS[0]}"="$NEXTVERSION; } | tee /tmp/aptstatus | dialog --progressbox $(tput lines) $(tput cols)
		elif [ $1 -eq 2 ]; then
			{ DEBIAN_FRONTEND=noninteractive eval nohup apt-get install -y ${VERSIONS[0]}"="$NEXTVERSION; rm -f /tmp/aptupdates; } >/tmp/aptstatus &
		fi
                getAptErrorCodeFn
                return $?
	fi
}
