#!/bin/bash

if [ $1 == "install" -o $1 == "upgrade" ]; then

	if [ -d "/usr/local/include/xbian-config/scripts" ]; then
		rm -r /usr/local/include/xbian-config/scripts
	fi
	
	if [ -f "/usr/local/include/xbian-config/dialogs" ]; then
		rm /usr/local/include/xbian-config/dialogs
	fi
	
	if [ -f "/usr/local/include/xbian-config/functions" ]; then
		rm /usr/local/include/xbian-config/functions
	fi
	
	if [ -f "/usr/local/include/xbian-config/prereqs" ]; then
		rm /usr/local/include/xbian-config/prereqs
	fi
	
	if [ -f "/usr/local/include/xbian-config/services" ]; then
		rm /usr/local/include/xbian-config/services
	fi
	
	if [ -f "/usr/local/include/xbian-config/struct" ]; then
		rm /usr/local/include/xbian-config/struct
	fi

	if [ ! -d "/etc/bash_completion.d" ]; then
		mkdir -p "/etc/bash_completion.d";
	fi

	if [ ! -d "/usr/local/sbin" ]; then
		mkdir -p "/usr/local/sbin";
	fi

	if [ ! -d "/usr/local/include/xbian-config/lang" ]; then
		mkdir -p "/usr/local/include/xbian-config/lang";
	fi

	if [ ! -d "/usr/local/include/xbian-config" ]; then
		mkdir -p "/usr/local/include/xbian-config";
	fi

	if [ ! -d "/usr/local/include/xbian-config/modules/videoflags" ]; then
		mkdir -p "/usr/local/include/xbian-config/modules/videoflags";
	fi

	if [ ! -d "/usr/local/include/xbian-config/modules/videoflags/lang" ]; then
		mkdir -p "/usr/local/include/xbian-config/modules/videoflags/lang";
	fi

	if [ ! -d "/usr/local/include/xbian-config/modules/timezone" ]; then
		mkdir -p "/usr/local/include/xbian-config/modules/timezone";
	fi

	if [ ! -d "/usr/local/include/xbian-config/modules/timezone/lang" ]; then
		mkdir -p "/usr/local/include/xbian-config/modules/timezone/lang";
	fi

	if [ ! -d "/usr/local/include/xbian-config/modules/kernel" ]; then
		mkdir -p "/usr/local/include/xbian-config/modules/kernel";
	fi

	if [ ! -d "/usr/local/include/xbian-config/modules/kernel/lang" ]; then
		mkdir -p "/usr/local/include/xbian-config/modules/kernel/lang";
	fi

	if [ ! -d "/usr/local/include/xbian-config/modules/updates" ]; then
		mkdir -p "/usr/local/include/xbian-config/modules/updates";
	fi

	if [ ! -d "/usr/local/include/xbian-config/modules/updates/lang" ]; then
		mkdir -p "/usr/local/include/xbian-config/modules/updates/lang";
	fi

	if [ ! -d "/usr/local/include/xbian-config/modules/resizesd" ]; then
		mkdir -p "/usr/local/include/xbian-config/modules/resizesd";
	fi

	if [ ! -d "/usr/local/include/xbian-config/modules/resizesd/lang" ]; then
		mkdir -p "/usr/local/include/xbian-config/modules/resizesd/lang";
	fi

	if [ ! -d "/usr/local/include/xbian-config/modules/information/lang" ]; then
		mkdir -p "/usr/local/include/xbian-config/modules/information/lang";
	fi

	if [ ! -d "/usr/local/include/xbian-config/modules/information" ]; then
		mkdir -p "/usr/local/include/xbian-config/modules/information";
	fi

	if [ ! -d "/usr/local/include/xbian-config/modules/xbmc" ]; then
		mkdir -p "/usr/local/include/xbian-config/modules/xbmc";
	fi

	if [ ! -d "/usr/local/include/xbian-config/modules/xbmc/lang" ]; then
		mkdir -p "/usr/local/include/xbian-config/modules/xbmc/lang";
	fi

	if [ ! -d "/usr/local/include/xbian-config/modules/sshroot" ]; then
		mkdir -p "/usr/local/include/xbian-config/modules/sshroot";
	fi

	if [ ! -d "/usr/local/include/xbian-config/modules/sshroot/lang" ]; then
		mkdir -p "/usr/local/include/xbian-config/modules/sshroot/lang";
	fi

	if [ ! -d "/usr/local/include/xbian-config/modules/xbconfig" ]; then
		mkdir -p "/usr/local/include/xbian-config/modules/xbconfig";
	fi

	if [ ! -d "/usr/local/include/xbian-config/modules/xbconfig/lang" ]; then
		mkdir -p "/usr/local/include/xbian-config/modules/xbconfig/lang";
	fi

	if [ ! -d "/usr/local/include/xbian-config/modules/network" ]; then
		mkdir -p "/usr/local/include/xbian-config/modules/network";
	fi

	if [ ! -d "/usr/local/include/xbian-config/modules/network/lang" ]; then
		mkdir -p "/usr/local/include/xbian-config/modules/network/lang";
	fi

	if [ ! -d "/usr/local/include/xbian-config/modules/licensevc1" ]; then
		mkdir -p "/usr/local/include/xbian-config/modules/licensevc1";
	fi

	if [ ! -d "/usr/local/include/xbian-config/modules/licensevc1/lang" ]; then
		mkdir -p "/usr/local/include/xbian-config/modules/licensevc1/lang";
	fi

	if [ ! -d "/usr/local/include/xbian-config/modules/xbianpass" ]; then
		mkdir -p "/usr/local/include/xbian-config/modules/xbianpass";
	fi

	if [ ! -d "/usr/local/include/xbian-config/modules/xbianpass/lang" ]; then
		mkdir -p "/usr/local/include/xbian-config/modules/xbianpass/lang";
	fi

	if [ ! -d "/usr/local/include/xbian-config/modules/overclocking" ]; then
		mkdir -p "/usr/local/include/xbian-config/modules/overclocking";
	fi

	if [ ! -d "/usr/local/include/xbian-config/modules/overclocking/lang" ]; then
		mkdir -p "/usr/local/include/xbian-config/modules/overclocking/lang";
	fi

	if [ ! -d "/usr/local/include/xbian-config/modules/rootpass" ]; then
		mkdir -p "/usr/local/include/xbian-config/modules/rootpass";
	fi

	if [ ! -d "/usr/local/include/xbian-config/modules/rootpass/lang" ]; then
		mkdir -p "/usr/local/include/xbian-config/modules/rootpass/lang";
	fi

	if [ ! -d "/usr/local/include/xbian-config/modules/hostname" ]; then
		mkdir -p "/usr/local/include/xbian-config/modules/hostname";
	fi

	if [ ! -d "/usr/local/include/xbian-config/modules/hostname/lang" ]; then
		mkdir -p "/usr/local/include/xbian-config/modules/hostname/lang";
	fi

	if [ ! -d "/usr/local/include/xbian-config/modules/licensempg2" ]; then
		mkdir -p "/usr/local/include/xbian-config/modules/licensempg2";
	fi

	if [ ! -d "/usr/local/include/xbian-config/modules/licensempg2/lang" ]; then
		mkdir -p "/usr/local/include/xbian-config/modules/licensempg2/lang";
	fi

	if [ ! -d "/usr/local/include/xbian-config/modules/packages" ]; then
		mkdir -p "/usr/local/include/xbian-config/modules/packages";
	fi

	if [ ! -d "/usr/local/include/xbian-config/modules/packages/lang" ]; then
		mkdir -p "/usr/local/include/xbian-config/modules/packages/lang";
	fi

	if [ ! -d "/usr/local/include/xbian-config/modules/services/lang" ]; then
		mkdir -p "/usr/local/include/xbian-config/modules/services/lang";
	fi

	if [ ! -d "/usr/local/include/xbian-config/modules/services" ]; then
		mkdir -p "/usr/local/include/xbian-config/modules/services";
	fi

	if [ ! -d "/usr/local/include/xbian-config/functions" ]; then
		mkdir -p "/usr/local/include/xbian-config/functions";
	fi

	if [ ! -d "/usr/local/include/xbian-config/config" ]; then
		mkdir -p "/usr/local/include/xbian-config/config";
	fi
	
fi