#!/bin/sh

PATH=/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin

. /etc/default/xbian-snap

[ "$ENABLEDSCHEDULE" = yes ] || exit 0
[ "$KEEPDAYS" -ne 0 ] || exit 0

btrfs-auto-snapshot -l daily -k $KEEPDAYS -v //
