#!/bin/sh

. /etc/default/xbian-snap

[ "$ENABLEDSCHEDULE" = yes ] || exit 0
[ "$KEEPMONTHS" -ne 0 ] || exit 0

while initctl list | grep "^xbian-xbmc-player" | grep -q "start/running"; do
  if status xbmc-screensaver | grep -q "start/running"; then
    break
  fi
  sleep 300 # 5 minutes
done

if [ -z "$EXCLUDESUB" ];
then
  TMPEXCLUDESUB=
else
  TMPEXCLUDESUB="-x $EXCLUDESUB"
fi
btrfs-auto-snapshot -l monthly -k $KEEPMONTHS -v $TMPEXCLUDESUB //

[ "$IMGPLAN" = monthly ] || exit 0 
[ "$IMGTYPE" = file ] && opt_img='--img'   
nice -n +1 /usr/sbin/btrfs-auto-snapshot xbiancopy $opt_img /dev/root $IMGDEST  > /dev/null 2>&1   
