#!/bin/bash
#
#Copyright 2012 - 2013 CurlyMo & mk01 <development@xbian.org>
#
#This file is part of XBian - XBMC on the Raspberry Pi.
#
#XBian is free software: you can redistribute it and/or modify it under the
#terms of the GNU General Public License as published by the Free Software
#Foundation, either version 3 of the License, or (at your option) any later
#version.
#
#XBian is distributed in the hope that it will be useful, but WITHOUT ANY
#WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
#FOR A PARTICULAR PURPOSE. See the GNU General Public License for more
#details.
#
#You should have received a copy of the GNU General Public License along
#with XBian. If not, see <http://www.gnu.org/licenses/>

function showXBMCSettingsDlg() {
	MENU=();
	MENU+=(1,"\Zn"$(_ xbmc.label.webserver));
	createTableFn "menu"\
	"#;\Zb"$(_ xbmc.label.actions)\
	"${MENU[@]}";

	centerTxtFn "$HEADER" $(($DEFAULTWIDTH+7))
	showMenuDlg "$CENTEREDTXT" "$ROWS" ${#MENU[@]} 10
}

function showXBMCWebserverDlg() {
	wrapTxtFn "$(_ xbmc.webserver.enable_disable)" $(($DEFAULTWIDTH-4));
	centerTxtFn "$WRAPPEDTXT" $(($DEFAULTWIDTH-4));
	valignTxtFn "$CENTEREDTXT"
	showConfirmDlg "$ALIGNEDTXT" $HEIGHT 55 "$(_ dialog.enable)" "$(_ dialog.disable)"
	return $?;
}

function showXBMCWebserverSuccessEnabledDlg() {
	wrapTxtFn "$(_ xbmc.webserver.enable.success)" $(($DEFAULTWIDTH-4));
	centerTxtFn "$WRAPPEDTXT" $(($DEFAULTWIDTH-4));
	valignTxtFn "$CENTEREDTXT"
	showMsgDlg "$ALIGNEDTXT" $HEIGHT;
}

function showXBMCWebserverSuccessDisabledDlg() {
	wrapTxtFn "$(_ xbmc.webserver.disable.success)" $(($DEFAULTWIDTH-4));
	centerTxtFn "$WRAPPEDTXT" $(($DEFAULTWIDTH-4));
	valignTxtFn "$CENTEREDTXT"
	showMsgDlg "$ALIGNEDTXT" $HEIGHT;
}

function showXBMCWebserverFailedEnableDlg() {
	wrapTxtFn "$(_ xbmc.webserver.enable.failed)" $(($DEFAULTWIDTH-4));
	centerTxtFn "$WRAPPEDTXT" $(($DEFAULTWIDTH-4));
	valignTxtFn "$CENTEREDTXT"
	showMsgDlg "$ALIGNEDTXT" $HEIGHT;
}

function showXBMCWebserverFailedDisableDlg() {
	wrapTxtFn "$(_ xbmc.webserver.disable.failed)" $(($DEFAULTWIDTH-4));
	centerTxtFn "$WRAPPEDTXT" $(($DEFAULTWIDTH-4));
	valignTxtFn "$CENTEREDTXT"
	showMsgDlg "$ALIGNEDTXT" $HEIGHT;
}
