#!/bin/bash
#
#Copyright 2012 CurlyMo <development@xbian.org>
#
#This file is part of XBian - XBMC on the Raspberry Pi.
#
#XBian is free software: you can redistribute it and/or modify it under the
#terms of the GNU General Public License as published by the Free Software
#Foundation, either version 3 of the License, or (at your option) any later
#version.
#
#XBian is distributed in the hope that it will be useful, but WITHOUT ANY
#WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
#FOR A PARTICULAR PURPOSE. See the GNU General Public License for more
#details.
#
#You should have received a copy of the GNU General Public License along
#with XBian. If not, see <http://www.gnu.org/licenses/>

# Sets the GUI resolution of XBMC
#  $1 Resolution [String] One of the available resolutions
# Returns
# - 0: Failed
# - 1: Success
function setXBMCGUIResFn() {
	NEWRES=$1;
	OLDRES=$(sed -ne 's/\(.*<guires>\)\([0-9]\{1,4\}\)\(<\/guires>\)/\2/p' /home/xbian/.xbmc/userdata/advancedsettings.xml);
	if [ -z "$OLDRES" ]; then
		if [ $(cat /home/xbian/.xbmc/userdata/advancedsettings.xml | grep -c "lookandfeel" ) -eq 2 ]; then
			sed -i "s/<\/lookandfeel>/     <guires>$NEWRES<\/guires>\n   <\/lookandfeel>/g" /home/xbian/.xbmc/userdata/advancedsettings.xml
		else
			sed -i "s/<\/advancedsettings>/   <lookandfeel>\n     <guires>$NEWRES<\/guires>\n   <\/lookandfeel>\n<\/advancedsettings>/g" /home/xbian/.xbmc/userdata/advancedsettings.xml
		fi
	else
		sed -i "s/<guires>$OLDRES<\/guires>/<guires>$NEWRES<\/guires>/g" /home/xbian/.xbmc/userdata/advancedsettings.xml
	fi
	if [ $(sed -ne 's/\(.*<guires>\)\([0-9]\{1,4\}\)\(<\/guires>\)/\2/p' /home/xbian/.xbmc/userdata/advancedsettings.xml | grep -c .) -eq 1 ]; then
		return 1;
	else
		return 0;
	fi
}

# Gets the GUI resolution of XBMC
# Returns
# - 0: Failed
# - @: Resolution
function getXBMCGUIResFn() {
	CURRES=$(sed -ne 's/\(.*<guires>\)\([0-9]\{1,4\}\)\(<\/guires>\)/\2/p' /home/xbian/.xbmc/userdata/advancedsettings.xml);
	if [ -z "$CURRES" ]; then
		return 0;
	else
		return $CURRES;
	fi
}

# Sets the webserver setting XBMC
#  $1: [Integer] 1 or 0
# Returns
# - 0: Failed
# - 1: Success
function setXBMCWebserverFn() {
        if [ $1 -eq 1 ]; then
                NEWSET="false";
        else
                NEWSET="true";
        fi
        OLDSET=$(sed -ne 's/\(.*<webserver>\)\([a-z]\{1,5\}\)\(<\/webserver>\)/\2/p' /home/xbian/.xbmc/userdata/advancedsettings.xml);
        if [ -z "$OLDSET" ]; then
                if [ $(grep -c "lookandfeel" /home/xbian/.xbmc/userdata/advancedsettings.xml) -eq 2 ]; then
                        sed -i "s/<\/lookandfeel>/     <webserver>$NEWSET<\/webserver>\n   <\/lookandfeel>/g" /home/xbian/.xbmc/userdata/advancedsettings.xml
                else
                        sed -i "s/<\/advancedsettings>/   <lookandfeel>\n     <webserver>$NEWSET<\/webserver>\n   <\/lookandfeel>\n<\/advancedsettings>/g" /home/xbian/.xbmc/userdata/advancedsettings.xml
                fi
        else
                sed -i "s/<webserver>$OLDSET<\/webserver>/<webserver>$NEWSET<\/webserver>/g" /home/xbian/.xbmc/userdata/advancedsettings.xml
        fi
        if [ "$(sed -ne 's/\(.*<webserver>\)\([a-z]\{1,5\}\)\(<\/webserver>\)/\2/p' /home/xbian/.xbmc/userdata/advancedsettings.xml)" == "$NEWSET" ]; then
                return 1;
        else
                return 0;
        fi
}

# Gets the webserver setting XBMC
# Returns
# - 0: Disabled
# - 1: Enabled
function getXBMCWebserverFn() {
	CURSET=$(sed -ne 's/\(.*<webserver>\)\([a-z]\{1,5\}\)\(<\/webserver>\)/\2/p' /home/xbian/.xbmc/userdata/advancedsettings.xml);
	if [ -z "$CURSET" ] || [ "$CURSET" == "false" ]; then
		return 0;
	else
		return 1;
	fi	
}
