#!/bin/bash

#Copyright 2012 CurlyMo <development@xbian.org>
#
#This file is part of XBian - XBMC on the Raspberry Pi.
#
#XBian is free software: you can redistribute it and/or modify it under the
#terms of the GNU General Public License as published by the Free Software
#Foundation, either version 3 of the License, or (at your option) any later
#version.
#
#XBian is distributed in the hope that it will be useful, but WITHOUT ANY
#WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
#FOR A PARTICULAR PURPOSE. See the GNU General Public License for more
#details.
#
#You should have received a copy of the GNU General Public License along
#with XBian. If not, see <http://www.gnu.org/licenses/>

function showWrongBlockDev() {
        wrapTxtFn "$(_ xbiancopy.dialog.wrongblkdev)" $(($DEFAULTWIDTH-4))
        centerTxtFn "$WRAPPEDTXT" $(($DEFAULTWIDTH-4))
        valignTxtFn "$CENTEREDTXT"
        showInfoDlg "$ALIGNEDTXT" $HEIGHT
        return $?;
}

function showConfigDialog() {
	IFS=" ";
	DATA=($1)
	IFS=$ORIGINALIFS;

	ELEMENTS=();
	ELEMENTS+=("1,3,$(_ xbiancopy.label.source),/dev/root,27,42,200,0");
	ELEMENTS+=("2,3,$(_ xbiancopy.label.dest),/dev/sdxx,27,42,200,0");
	
	showInputFormDlg "	
If you want to create .img file with /boot partition and your system, specify \"file:\" as prefix to destination 
(e.g. file:/media/exthdd/xbian.img)
    
Otherwise specify block device 
(e.g. /dev/sda2)
    
!!! PARTITION WILL BE REFORMATTED !!!
" 17 75
} 
