#!/bin/bash

#Copyright 2012 - 2017 CurlyMo & mkreisl <development@xbian.org>
#
#This file is part of XBian - XBMC on the Raspberry Pi.
#
#XBian is free software: you can redistribute it and/or modify it under the
#terms of the GNU General Public License as published by the Free Software
#Foundation, either version 3 of the License, or (at your option) any later
#version.
#
#XBian is distributed in the hope that it will be useful, but WITHOUT ANY
#WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
#FOR A PARTICULAR PURPOSE. See the GNU General Public License for more
#details.
#
#You should have received a copy of the GNU General Public License along
#with XBian. If not, see <http://www.gnu.org/licenses/>

function showUmountFormatError() {
        wrapTxtFn "$(_ xbiancopy.dialog.preperror)" $(($DEFAULTWIDTH-4))
        centerTxtFn "$WRAPPEDTXT" $(($DEFAULTWIDTH-4))
        valignTxtFn "$CENTEREDTXT"
        showInfoDlg "$ALIGNEDTXT" $HEIGHT
        return $?;
}

function showNFSerror() {
        wrapTxtFn "$(_ xbiancopy.dialog.exportwrong)" $(($DEFAULTWIDTH-4))
        centerTxtFn "$WRAPPEDTXT" $(($DEFAULTWIDTH-4))
        valignTxtFn "$CENTEREDTXT"
        showInfoDlg "$ALIGNEDTXT" $HEIGHT
        return $?;
}

function showWrongBlockDev() {
        wrapTxtFn "$(_ xbiancopy.dialog.wrongblkdev)" $(($DEFAULTWIDTH-4))
        centerTxtFn "$WRAPPEDTXT" $(($DEFAULTWIDTH-4))
        valignTxtFn "$CENTEREDTXT"
        showInfoDlg "$ALIGNEDTXT" $HEIGHT
        return $?;
}

function showConfigDialog() {
	IFS=" ";
	DATA=($1)
	IFS=$ORIGINALIFS;

	ELEMENTS=();
	ELEMENTS+=("1,3,$(_ xbiancopy.label.source),/dev/root,27,42,200,0");
	ELEMENTS+=("2,3,$(_ xbiancopy.label.dest),/dev/sdX,27,42,200,0");
	
	showInputFormDlg "	
If you want to create .img file with /boot partition and your system, specify \"file:\" as prefix to destination 
(e.g. file:/media/exthdd/xbian.img)
    
If you want to convert to NFS ROOT installation, put \"nfs[{3,4}]:\" as prefix to NFS export specification
(use IP address, not host-names. NFS export needs \"no_root_squash\" option)
(e.g. nfs:192.168.3.12:/nas-exports/rpi-nfs-root)
    
Otherwise specify block device 
(e.g. /dev/sda2)
    
 !!!  WARNING: Destination partition/NFS export WILL BE WIPED OUT  !!!
" 23 75
} 
