#!/bin/bash
#
#Copyright 2012 CurlyMo <development@xbian.org>
#
#This file is part of XBian - XBMC on the Raspberry Pi.
#
#XBian is free software: you can redistribute it and/or modify it under the
#terms of the GNU General Public License as published by the Free Software
#Foundation, either version 3 of the License, or (at your option) any later
#version.
#
#XBian is distributed in the hope that it will be useful, but WITHOUT ANY
#WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
#FOR A PARTICULAR PURPOSE. See the GNU General Public License for more
#details.
#
#You should have received a copy of the GNU General Public License along
#with XBian. If not, see <http://www.gnu.org/licenses/>


backupImgPlanFn() {
    [ -z "$1" ] && { grep IMGPLAN= /etc/default/xbian-snap | awk -F'=' '{print $2}'; exit 0; }
    case $1 in
        none|daily|weekly|monthly)
            eval sed -i 's/IMGPLAN=.*/IMGPLAN=$1/' /etc/default/xbian-snap
            echo 1
            ;;
        *)
            echo -1
            ;;
    esac
}
backupImgTypeFn() {
    [ -z "$1" ] && { grep IMGTYPE= /etc/default/xbian-snap | awk -F'=' '{print $2}'; exit 0; }
    case $1 in
        "block"|"file")
            eval sed -i 's/IMGTYPE=.*/IMGTYPE=$1/' /etc/default/xbian-snap
            echo 1
            ;;
        *)
            echo -1
            ;;
    esac
}
backupImgDestFn() {
    [ -z "$1" ] && { grep IMGDEST= /etc/default/xbian-snap | awk -F'=' '{print $2}' | tr -d \"; exit 0; }
    [ "$1" = "?" ] && { . /etc/default/xbian-snap; echo $IMGDEST; exit 0; }
    tt=$(backupImgTypeFn)
    case $tt in
        block)
            [ ! -b "$1" ] && { echo -1; exit 0; }
            ;;
        file)
            echo f=\"$1\" > /run/xbiancopy.tmp; . /run/xbiancopy.tmp; rm /run/xbiancopy.tmp
            [ ! -e "$f" ] && fdel=1
            ! touch "$f" 2>/dev/null && { echo -1; exit 0; }
            [ "$(df -P "$f" | tail -1 | awk '{print $f}')" = "$(readlink -e /dev/root)" ] && { [ -n "$fdel" ] && rm "$f"; echo -2; exit 0; }
            [ -n "$fdel" ] && rm "$f"
            ;;
        *)
            { echo -1; exit 0; }
    esac
    eval sed -i 's\@IMGDEST=.*@IMGDEST=\"$1\"@' /etc/default/xbian-snap
    echo 1
}

getImgPartitionsFn(){
    printf "%s;" $(blkid | grep -v "$(readlink -e /dev/root)\|mmcblk0p1\|zram\|loop\|$(blkid -t TYPE=swap -o device)"| awk -F':' '{print $1}')
}

dailySnapFn() {
    sch=0
    case $1 in
        '')
            grep -q ENABLEDSCHEDULE=yes /etc/default/xbian-snap && sch=1
            nr=$(grep KEEPDAYS= /etc/default/xbian-snap| awk -F'=' '{print $2}')
            [ $sch -eq 1 -a $nr -gt 0 ] && echo "1 $nr" || echo "0"
            ;;
        *)
            eval sed -i 's/KEEPDAYS=.*/KEEPDAYS=$1/' /etc/default/xbian-snap
            grep -q KEEPDAYS=$1 /etc/default/xbian-snap && echo 1 || echo 0
            ;;
    esac
}

weeklySnapFn() {
    sch=0
    case $1 in
        '')
            grep -q ENABLEDSCHEDULE=yes /etc/default/xbian-snap && sch=1
            nr=$(grep KEEPWEEKS= /etc/default/xbian-snap| awk -F'=' '{print $2}')
            [ $sch -eq 1 -a $nr -gt 0 ] && echo "1 $nr" || echo "0"
            ;;
        *)
            eval sed -i 's/KEEPWEEKS=.*/KEEPWEEKS=$1/' /etc/default/xbian-snap
            grep -q KEEPWEEKS=$1 /etc/default/xbian-snap && echo 1 || echo 0
            ;;
    esac
}

monthlySnapFn() {
    sch=0
    case $1 in
        '')
            grep -q ENABLEDSCHEDULE=yes /etc/default/xbian-snap && sch=1
            nr=$(grep KEEPMONTHS= /etc/default/xbian-snap| awk -F'=' '{print $2}')
            [ $sch -eq 1 -a $nr -gt 0 ] && echo "1 $nr" || echo "0"
            ;;
        *)
            eval sed -i 's/KEEPMONTHS=.*/KEEPMONTHS=$1/' /etc/default/xbian-snap
            grep -q KEEPMONTHS=$1 /etc/default/xbian-snap && echo 1 || echo 0
            ;;
    esac
}
