#!/bin/bash
#
#Copyright 2012 CurlyMo <development@xbian.org>
#
#This file is part of XBian - XBMC on the Raspberry Pi.
#
#XBian is free software: you can redistribute it and/or modify it under the
#terms of the GNU General Public License as published by the Free Software
#Foundation, either version 3 of the License, or (at your option) any later
#version.
#
#XBian is distributed in the hope that it will be useful, but WITHOUT ANY
#WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
#FOR A PARTICULAR PURPOSE. See the GNU General Public License for more
#details.
#
#You should have received a copy of the GNU General Public License along
#with XBian. If not, see <http://www.gnu.org/licenses/>

# Get the current hostname
#  $1 [Container] Hostname
# Returns
#  $HOSTNAME [String]
function getCurrentHostnameFn() {
	HOSTNAME=$(cat /etc/hostname);
}

# Get the current hostname
#  $1 [String] New hostname
#  $2 [String] Old hostname
# Returns
#  * [Integer]
#  - 1: Success
#  - 0: Failed
function setHostnameFn() {
	echo "$1" > /etc/hostname
	hostname -F /etc/hostname
	eval "sed -i 's/$2 /$1 /g' /etc/hosts";
	eval "sed -i 's/$2\t/$1\t/g' /etc/hosts";
	eval "sed -i 's/$2\./$1\./g' /etc/hosts";
	eval "sed -i 's/<devicename>.*<\/devicename>/<devicename>$1<\/devicename>/' /home/xbian/.xbmc/userdata/guisettings.xml"
	if [ $(hostname) == $1 ]; then
		return 1;
	else
		return 0;
	fi

}
