#!/bin/bash
#
#Copyright 2012 - 2017 CurlyMo & mkreisl <development@xbian.org>
#
#This file is part of XBian - XBMC on the Raspberry Pi.
#
#XBian is free software: you can redistribute it and/or modify it under the
#terms of the GNU General Public License as published by the Free Software
#Foundation, either version 3 of the License, or (at your option) any later
#version.
#
#XBian is distributed in the hope that it will be useful, but WITHOUT ANY
#WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
#FOR A PARTICULAR PURPOSE. See the GNU General Public License for more
#details.
#
#You should have received a copy of the GNU General Public License along
#with XBian. If not, see <http://www.gnu.org/licenses/>
#

# remove Raspberry PI config variable
#  $1 [String] Key
deleteConfigVarFn() {
	sed -i "/^$1=/d" /boot/config.txt
}

# update/insert Raspberry PI config variable
#  $1 [String] Key
#  $2 [Mixed] Value
#  $3 [String] e: Delete empty lines
#              n: Do now write 0 values
updateConfigVarFn() {
	if [[ x"$3" =~ n ]] && [ "$2" == 0 ]; then
	    deleteConfigVarFn $1
	elif grep -q ^"$1" /boot/config.txt; then
	    sed -i "s/^$1=.*/$1=$2/g" /boot/config.txt
	else
	    echo -e "$1=$2" >> /boot/config.txt
	fi
	[[ x"$3" =~ e ]] && sed -i '/^$/d' /boot/config.txt
}

# select Raspberry PI config variable
#  $1 [String] Key
selectConfigVarFn() {
	RETURN="$(sed 's/[ \t]//g' /boot/config.txt | grep ^"${1}")"
}
