#!/bin/bash

_module_=$MODULE
#|------------------------------------|
#|          Global variables          |
#|------------------------------------|

# The arguments this module accepts
ARGUMENTS=(list);

#|------------------------------------|
#|          Include files             |
#|------------------------------------|

. $BASEPATH/modules/$_module_/functions
if [ $GUIMODE -eq 1 ]; then
        . $BASEPATH/modules/$_module_/dialogs
fi

function showGUIFn() 
{

case $MODULE in
        updatemirrors)
#                showDownloadPackageListDlg
                if ! updateAptMirrorsFn; then
                        showFailedToRetrieveAptMirrosDlg
                else
                        showDownloadPackageListDlg
			downloadPackageListFn
                        #REMOTEPKGDBUPDATED=$?
                fi
                ;;
        aptupdate)
                updateAptFn speak | dialog --programbox 30 70 
                ;;
                *)
                ;;
esac

}

