#!/bin/bash
#
#Copyright 2012 CurlyMo <development@xbian.org>
#
#This file is part of XBian - XBMC on the Raspberry Pi.
#
#XBian is free software: you can redistribute it and/or modify it under the
#terms of the GNU General Public License as published by the Free Software
#Foundation, either version 3 of the License, or (at your option) any later
#version.
#
#XBian is distributed in the hope that it will be useful, but WITHOUT ANY
#WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
#FOR A PARTICULAR PURPOSE. See the GNU General Public License for more
#details.
#
#You should have received a copy of the GNU General Public License along
#with XBian. If not, see <http://www.gnu.org/licenses/>

exit 0

#|------------------------------------|
#|          Global variables          |
#|------------------------------------|

# The arguments this module accepts
ARGUMENTS=(info);

#|------------------------------------|
#|          Include files             |
#|------------------------------------|

source $BASEPATH/modules/resizesd/functions
if [ $GUIMODE -eq 1 ]; then
	source $BASEPATH/modules/resizesd/dialogs
fi

#|------------------------------------|
#|           Main program             |
#|------------------------------------|

# Executes the GUI version of this module
function showGUIFn() {
			showSDResizeNotNeededDlg;
}

# Executes the command line version of this module
#  $1 Argument [String]
# Returns
#  *Update [Integer]
#  - 1: Success
#  - 0: Failed
#  check
#  -1: Already resized
#  resize
#  -1: Already resized
#  -2: Wrong number of arguments
function showCMDFn() {
	case $1 in
		check)
			if [ $# -eq 1 ]; then
				checkNeedToResizeFn;
				if [ $? -eq 1 ]; then
					echo 1;
				else
					echo -1;
				fi
			else
				echo -2;
			fi
		;;
	esac;
}