#!/bin/bash
#
#Copyright 2012 CurlyMo <development@xbian.org>
#
#This file is part of XBian - XBMC on the Raspberry Pi.
#
#XBian is free software: you can redistribute it and/or modify it under the
#terms of the GNU General Public License as published by the Free Software
#Foundation, either version 3 of the License, or (at your option) any later
#version.
#
#XBian is distributed in the hope that it will be useful, but WITHOUT ANY
#WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
#FOR A PARTICULAR PURPOSE. See the GNU General Public License for more
#details.
#
#You should have received a copy of the GNU General Public License along
#with XBian. If not, see <http://www.gnu.org/licenses/>

# Shows the dialog in which users can choose to disable or enable root login through ssh
# Returns
#  $? [Integer]
#  - 1: Enable ssh root login
#  - 0: Disable ssh root login
function enableDisableSSHRootLoginDlg() {
	wrapTxtFn "$(_ sshroot.enable_confirm)" $(($DEFAULTWIDTH-20));
	centerTxtFn "$WRAPPEDTXT" $(($DEFAULTWIDTH-20));
	valignTxtFn "$CENTEREDTXT"
	showConfirmDlg "$ALIGNEDTXT" $HEIGHT 55 "$(_ dialog.enable)" "$(_ dialog.disable)"
	return $?;
}

# Warns the user that no root password was given, a requirement for ssh root login
function showEmptyRootPasswordDlg() {
	wrapTxtFn "$(_ sshroot.empty_password)" $(($DEFAULTWIDTH-4));
	centerTxtFn "$WRAPPEDTXT" $(($DEFAULTWIDTH-4));
	valignTxtFn "$CENTEREDTXT"
	showMsgDlg "$ALIGNEDTXT" $HEIGHT;
}

# Shows a message that the SSH root login was disabled
function showSSHRootDisabledDlg() {
	wrapTxtFn "$(_ sshroot.disabled)" $(($DEFAULTWIDTH-4));
	centerTxtFn "$WRAPPEDTXT" $(($DEFAULTWIDTH-4));
	valignTxtFn "$CENTEREDTXT"
	showMsgDlg "$ALIGNEDTXT"
}

# Shows a message that the SSH root login was enabled
function showSSHRootEnabledDlg() {
	wrapTxtFn "$(_ sshroot.enabled)" $(($DEFAULTWIDTH-4));
	centerTxtFn "$WRAPPEDTXT" $(($DEFAULTWIDTH-4));
	valignTxtFn "$CENTEREDTXT"
	showMsgDlg "$ALIGNEDTXT"
}
